### ISSUE TITLE
mini rackstack stl

### ISSUE THREAD

**Issue by krnewberry** [jazwa/rackstack#1]
unable to load up stls in slicer (bambu studio) -- specifically the mainrail_p.stl (mini folder) downloads at 445bytes.. there are several others behaving similarly.
'unable to load file: the file does not contain any geometry data'

**Comment by jazwa** [comment]
`mainrail_p.stl` shouldn't be only 445bytes: https://github.com/jazwa/rackstack/blob/main/stl/mini/rack/mainRail_P.stl (latest is 363 KB) Could you please try pulling the latest main? (or using the latest release)

**Comment by krnewberry** [comment]
odd!! it works perfectly now. sorry that must have been on my end or github. Thanks for the quick reply.
