### ISSUE TITLE
rack-mount stls

### ISSUE THREAD

**Issue by Siopaos** [jazwa/rackstack#10]
Dear Jazwa,
Thank you for your great work! Could you include the .stls for the beelink trays you made online? I fear I am too ignorant to create the .stl for a mini pc tray myself, and these would probably fit for me anyways.
Kind regards

**Comment by jazwa** [comment]
I've added the config for this here: https://github.com/jazwa/rackstack/blob/main/rack-mount/catalog/beelink-mini-s-tray.scad

So all you should need to do is open the file using OpenSCAD, and then click on generate and save stl.
