### ISSUE TITLE
Can't find rack-stack seen on the readme picture

### ISSUE THREAD

**Issue by GuideAuBug73** [jazwa/rackstack#14]
Hello,

I wanted to know if it's possible to print the rack stack that can be seen in the repo picture . It would be really useful for my project.

![image](https://github.com/user-attachments/assets/6533463a-a672-4dd0-a6ae-05bc587415db)

Thank you in advance for your help.
And thank you for the work done on this project !

**Comment by chaimt** [comment]
me too

**Comment by jazwa** [comment]
I just added a mounting system for these brackets: [here](https://github.com/jazwa/rackstack/tree/main/rack-mount/angle-bracket). Just open up the `entry.scad` file in that directory with OpenSCAD and configure as you wish.
