### ISSUE TITLE
Is 1.2.0 compatible with 1.1.1

### ISSUE THREAD

**Issue by kpoxo6op** [jazwa/rackstack#17]
hello,

I orderd to print some of the `1.1.1` details in a local library. `1.2.0` was released while I was waiting.

My 1.1.1. printed details

```text
sideWallLeft_P  - 1x
sideWallRight_P - 1x
xyPlate_P       - 2x
xBar_P.stl      - 4x
yBar_P.stl      - 4x
```

Is 1.2.0 compatible with 1.1.1? Thanks.

**Comment by jazwa** [comment]
Yes they should be. The only difference is that the yBars in `1.2.0` have the side modules attached to it already (like the hinge and magnet holders). The newer version just simplifies assembly and reduces the number of parts. How the parts fit together has not changed.

**Comment by kpoxo6op** [comment]
>  side modules attached to it already

Just assembled my `v1.1.1`! Here is how `1.2.0` would be simpler.

`1.1.1` VS `1.2.0`
![v111-v120](https://github.com/user-attachments/assets/9d239163-cde1-4585-adf4-0ac7daf1458c)

`1.1.1`: need to glue magnet and hinge holders
![v1 1 1](https://github.com/user-attachments/assets/26d7e5a0-7495-4232-b498-579fb0300124)

`1.2.0`: magnet and hinge holders are built in
![1 2 0](https://github.com/user-attachments/assets/fee4f417-ec5f-4737-bd3b-53f5203617ae)
