### ISSUE TITLE
How can I generate rack-mount items?

### ISSUE THREAD

**Issue by marcelbaarsch** [jazwa/rackstack#2]
Can I use rbuild.py to generate an stl of rack-mount items such as patchPanel?

**Comment by jazwa** [comment]
Not currently. For rack-mount items, I just suggest firing up Openscad (the program) and building the `entry.scad` file manually. 
For patch panels it would be https://github.com/jazwa/rackstack/blob/main/rack-mount/patch-panel/entry.scad
