### ISSUE TITLE
[Feature Request] Would you ever consider making a version where the larger parts are laser cut? 

### ISSUE THREAD

**Issue by rainyskye** [jazwa/rackstack#5]
Only saying this as it could cut down on a lot of print times, and you could still produce a clean and interesting design using specific woods/acrylics (depending on flammability/safety treating)

**Comment by drewgates** [comment]
An interesting idea. This would also make it producible out of steel or aluminum via SendCutSend or similar.

**Comment by rainyskye** [comment]
True, I didn't even think of that to be honest, that would be more suitable to lab hardware :)

**Comment by jazwa** [comment]
A lot of parts use specific geometries tailored for 3d printing; I don't know if they would be suitable for other fabrication methods. I think there's potential for the side+top panels to be laser cut? I don't have access to a laser cutter, so I can't really say. Tbh adding support for other fabrication methods (for this project) isn't really on my radar, but forks/prs are always welcome.

There are also some metal 3d printing services offered online though, if you're willing to shell out big bucks.
